#Game language
lang: "en_En"

#if true then only main commands will be listed
#if false also overloads commands will be listed
only-main-commands: true

#Game Settings
settings:
  # The time once the game starts, how long they are safe from PvP (In seconds)
  free-roam: 25
  # Maximum amount of items that will spawn in chests
  max-chestcontent: 5
  # Minimum amount of items that will spawn in chests
  min-chestcontent: 1
  # Maximum amount of items that will spawn in bonus chests
  max-bonus-chestcontent: 5
  # Minimum amount of items that will spawn in bonus chests
  min-bonus-chestcontent: 1
  globalexit:
    enable: false
    level: world
    x: 0
    y: 0
    z: 0

#Rollback Settings
rollback:
  # Let players break blocks in the arena, and restore when the game is done
  allow-block-break: false
  # When enabled, will not allow players to break blocks during the free-roam time
  protect-during-cooldown: true
  # Prevent players from trampling crops in your arenas
  prevent-trampling: true
  # List of blocks players can break (use ALL for all blocks)
  editable-blocks:
    - TALLGRASS
    - LEAVES
    - LEAVES2

#Final Settings
final:
  # When the game has x seconds left, teleport the players back to their starting point
  enabled: false
  # The time in seconds to announcement of
  # teleporting players back to their starting point
  # (note: increments of 30, ex: 30, 60, 90, 120, etc)
  countdown-start: 60
  # The time in seconds to stop announcement of
  # teleporting players back to their starting point
  countdown-end: 50
  # The time in seconds of freezing people before
  # final fight will begin
  countdown-freeze: 5
  # Final border size from the first spawn you set
  radius: 60

#Spectate Settings
# When enabled players can spectate games without interfering with players in the game
spectate:
  # Disabled by default
  enabled: false
  # When a player dies, they will automatically be put into spectator
  on-death: true
  # Players can chat in spectate
  chat: false

#Wand
wand:
  id: "blaze_rod"
  name: "&3HungerGames Wand"
  lore:
    - "&7Left-Click to set position 1"
    - "&7Right-Click to set position 2"

